conf = {
    "topics":{
        "mood_light":{
            "topic":"nightlightChain",
            "type":"onechannel"
        },
        "light":{
            "topic":"nightlightChain",
            "type":"onechannel"
        },
       "ambient_light":{
            "topic":"ambiLight",
            "type":"rgb"
        },
        "heater":{
            "topic":"heizung",
            "type":"heater"
        },
        "zoe":{
            "topic":"zoeRainbow",
            "type":"zoe"
        },
        "all_light":{
            "topic":"fullLight",
            "type":"rgb"
        },
        "licht":{
            "topic":"fullLight",
            "type":"rgb"
        },
        "lichterkette":{
            "topic":"nightlightChain",
            "type":"onechannel"
        },
       "ambilight":{
            "topic":"ambiLight",
            "type":"rgb"
        },
       "hintergrundbeleuchtung":{
            "topic":"ambiLight",
            "type":"rgb"
        },
        "alles_licht":{
            "topic":"fullLight",
            "type":"rgb"
        },
        "heizung":{
            "topic":"heizung",
            "type":"heater"
        },
        "sechseck":{
            "topic":"zoeRainbow",
            "type":"zoe"
        },
        "hauptlicht":{
            "topic":"mainLight",
            "type":"toggle"
        }
    },
    "types":{
        "toggle":{
            "an":1,
            "aus":0
        },
        "onechannel":{
            "on":100,
            "off":0,
            "an":100,
            "aus":0,
            "50":50,
            "10":10,
            "5":5,
            "0":0
        },
        "rgb":{
            "on":0xffffff,
            "off":0x000000,
            "red":0xff0000,
            "blue":0x0000ff,
            "green":0x00ff00,
            "an":0xffffff,
            "aus":0x000000,
            "rot":0xff0000,
            "blau":0x0000ff,
            "grün":0x00ff00,
            "50":0x707070,
            "100":0xffffff,
            "10":0x1f1f1f,
            "5":0x0f0f0f
        },
        "heater":{
            "on":20,
            "off":0,
            "0":0,
            "19":19,
            "20":20,
            "21":21,
            "an":20,
            "aus":0,
        },
        "zoe":{
            "on":1,
            "off":0,
            "an":1,
            "aus":0
        }
    }
}