homeassistant: false
frontend: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  port: /dev/ttyACM0
devices:
  '0x00178801102ead3f':
    friendly_name: mainlight
    transition: 0.5
